### ISSUE TITLE
Is 11GB GPU the minimum requirements?

### ISSUE THREAD

**Issue by Njasa2k** [YBYBZhang/ControlVideo#1]

**Comment by YBYBZhang** [comment]
Yes, all videos  (resolution 512x512) are produced using a 2080Ti with 11GB, including both short videos (~15 frames) and long videos (~100 frames).

**Comment by YBYBZhang** [comment]
Yes, all videos are produced using a 2080Ti with 11GB, including both short videos (~15 frames) and long videos (~100 frames).
