### ISSUE TITLE
controlnet-aux==0.0.6 ValueError: depth is not a valid processor id

### ISSUE THREAD

**Issue by CHNxindong** [YBYBZhang/ControlVideo#22]
Thanks for your great work. I can inference the code when condition == 'canny'. 

But when I inference the code with controlnet-aux==0.0.6 and condition == "depth". There is an error reported:  
ValueError: depth is not a valid processor id. Please make sure to choose one of scribble_hed, softedge_hed, scribble_hedsafe, softedge_hedsafe, depth_midas, mlsd, openpose, openpose_face, openpose_faceonly, openpose_full, openpose_hand, scribble_pidinet, softedge_pidinet, scribble_pidsafe, softedge_pidsafe, normal_bae, lineart_coarse, lineart_realistic, lineart_anime, depth_zoe, depth_leres, depth_leres++, shuffle, mediapipe_face, canny. 

Do you have some suggestions? 

![image](https://github.com/YBYBZhang/ControlVideo/assets/20262070/3ece9e3b-f40e-424b-be1e-c9dfde589666)

**Comment by YBYBZhang** [comment]
This error may be caused by the updated controlnet-aux version. You can try to set condition=="depth_midas".

**Comment by CHNxindong** [comment]
> This error may be caused by the updated controlnet-aux version. You can try to set condition=="depth_midas".

Thanks very much! I'll try it.
