### ISSUE TITLE
Typo in NEG_prompt

### ISSUE THREAD

**Issue by dhruvhacks** [YBYBZhang/ControlVideo#25]
The `fewer difits` should have been `fewer digits` IMO.

- https://github.com/YBYBZhang/ControlVideo/blob/8f8a5152005c85ff76f0fa25634b66294e7054a3/inference.py#L62C87-L62C99
- https://github.com/YBYBZhang/ControlVideo/blob/8f8a5152005c85ff76f0fa25634b66294e7054a3/predict.py#L38C87-L38C99

**Comment by YBYBZhang** [comment]
Thanks for your suggestions! Fixed it~

**Comment by dhruvhacks** [comment]
Closing this issue. Resolved by commit 4eac95f722bad014bbd42932795a33212ed417a1
