### ISSUE TITLE
pretrained file

### ISSUE THREAD

**Issue by xua222** [YBYBZhang/ControlVideo#34]
Hello, which pre-trained model do I need to import in this line of code, and which specific folder do I store it in after downloading it, I have downloaded all the weights you need in your readme file, but this line of code is reporting an error because the server does not have internet access.
processor = processor.from_pretrained("lllyasviel/Annotators")

**Comment by YBYBZhang** [comment]
Hi, you can directly download the required weights from https://huggingface.co/lllyasviel/Annotators in the directory "checkpoints/Annotators", and change this line of code into `processor = processor.from_pretrained("checkpoints/Annotators")`. 
For example, if `--condition` is set `depth_midas`, you just need to download https://huggingface.co/lllyasviel/Annotators/blob/main/dpt_hybrid-midas-501f0c75.pt
