### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [YBYBZhang/ControlVideo#4]
![image](https://github.com/YBYBZhang/ControlVideo/assets/36565076/2a91faf9-44da-4623-87e3-ac6315733870)

**Comment by YBYBZhang** [comment]
I think that the changed version of  `controlnet-aux`  leads to this problem.
I use the version controlnet-aux==0.0.1, which returns both depth and normal maps.
The latest version controlnet-aux==0.0.4 returns depth maps by default.
I have updated the code to support both of them !
