### ISSUE TITLE
no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory checkpoints/stable-diffusion-v1-5

### ISSUE THREAD

**Issue by didoll-john** [YBYBZhang/ControlVideo#5]
git clone fro https://huggingface.co/runwayml/stable-diffusion-v1-5
and it looks like this
ls
flownet.pkl  sd-controlnet-canny  sd-controlnet-depth  sd-controlnet-openpose  stable-diffusion-v1-5
but when I run the inference.py, there is an ERROR.
no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory checkpoints/stable-diffusion-v1-5
I checked the file in my directory, it's same as the file on https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main
what's my wrong?

**Comment by didoll-john** [comment]
<img width="592" alt="image" src="https://github.com/YBYBZhang/ControlVideo/assets/134175197/0be79f1f-d525-4f70-b524-70ef09dc8388">

**Comment by YBYBZhang** [comment]
Maybe some files in text_encoder/unet/vae are not successfully downloaded, could you provide me your error snapshot?

**Comment by didoll-john** [comment]
sure
<img width="819" alt="image" src="https://github.com/YBYBZhang/ControlVideo/assets/134175197/1fbea1eb-a75a-455b-8b62-9e4f30aaccc7">
and, you are right, I use git pull, and it said "Already up to date." but I checked the folder, some file missing

**Comment by YBYBZhang** [comment]
I also download this repo multiple times to get all files :)

**Comment by somenewaccountthen** [comment]
I am here now.. guess i persevere.

(As it's clone and i have LFS on and it's 20G+.. it might take a while. So be lucky/patient i guess)

'git lfs clone' is our friend  to see LFS progress. Downloads already running so i can't test :P (Needs lfs installed)
