### ISSUE TITLE
cfa-vram

### ISSUE THREAD

**Issue by dlutzzw** [YBYBZhang/ControlVideo#7]
hi, thanks for your excellent work. I'm confused about one question. In my impression, the VRAM that the text2video-zero model occup will increase as the number of frames referenced by cross-frame attention. Why do you use full cross-frame attention but only need 2080ti---only 11GB?

**Comment by YBYBZhang** [comment]
Thanks for your attention!
For short video generation (less than 15 frames), our ControlVideo is implemented with xFormers, so fully cross-frame only slightly increases the memory requirement.
For long video generation (about 100 frames), we adopt hierarchical sampling, which splits a long video into multiple short clips ( about 10 frames) and produce them clip-by-clip with long coherency.
Thus, both short and long videos could be efficiently produced with a 2080ti !

**Comment by dlutzzw** [comment]
I see, thanks for your reply!

**Comment by dlutzzw** [comment]
hi, I'm alse confused about the timesteps of interleaved-frame smoother. The paper says that : "interleaved-frame smoother is performed on predicted RGB frames at timesteps {30, 31} by default" ,  But your code use 19, 20 as default. How is this parameter determined， Why not do smoother on all DDIM steps？Have you done ablation for this part of the experiment? I don't seem to see it in the paper.
