### ISSUE TITLE
The size of tensor a (30) must match the size of tensor b (16) at non-singleton dimension 2

### ISSUE THREAD

**Issue by Laidawang** [YBYBZhang/ControlVideo#9]
Hello! thank you for your excellent work. When i try to use a video of 912 * 512，i changed the height and width in video_reading here:
![image](https://github.com/YBYBZhang/ControlVideo/assets/85244566/3a19ad98-4566-4db9-a0d1-f8bf48198094)
But i still got error: The size of tensor a (30) must match the size of tensor b (16) at non-singleton dimension 2
![image](https://github.com/YBYBZhang/ControlVideo/assets/85244566/cd20cd3c-7163-414a-89b3-09dd2319309a)

**Comment by YBYBZhang** [comment]
Thanks for pointing it out! We have added `--width` and `--height` parameters in `inference.sh` script, and you could change the size of video through them.
